apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: smart-e-commerce-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-05-10T22:58:04.176541',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline for e-commerce
      data processing and ML", "name": "Smart E-commerce Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: smart-e-commerce-pipeline
  templates:
  - name: data-processing
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def data_processing():
            return "Data processing completed"

        import argparse
        _parser = argparse.ArgumentParser(prog='Data processing', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = data_processing(**_parsed_args)
      image: python:3.7
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          data_processing():\n    return \"Data processing completed\"\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Data processing'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = data_processing(**_parsed_args)\n"],
          "image": "python:3.7"}}, "name": "Data processing"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: data-scraping
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def data_scraping():
            return "Data scraping completed"

        import argparse
        _parser = argparse.ArgumentParser(prog='Data scraping', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = data_scraping(**_parsed_args)
      image: python:3.7
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          data_scraping():\n    return \"Data scraping completed\"\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Data scraping'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = data_scraping(**_parsed_args)\n"],
          "image": "python:3.7"}}, "name": "Data scraping"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: deploy-model
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def deploy_model():
            return "Model deployment completed"

        import argparse
        _parser = argparse.ArgumentParser(prog='Deploy model', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = deploy_model(**_parsed_args)
      image: python:3.7
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          deploy_model():\n    return \"Model deployment completed\"\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Deploy model'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = deploy_model(**_parsed_args)\n"],
          "image": "python:3.7"}}, "name": "Deploy model"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: ml-training
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def ml_training():
            return "ML training completed"

        import argparse
        _parser = argparse.ArgumentParser(prog='Ml training', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = ml_training(**_parsed_args)
      image: python:3.7
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          ml_training():\n    return \"ML training completed\"\n\nimport argparse\n_parser
          = argparse.ArgumentParser(prog=''Ml training'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = ml_training(**_parsed_args)\n"],
          "image": "python:3.7"}}, "name": "Ml training"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: model-evaluation
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def model_evaluation():
            return "Model evaluation completed"

        import argparse
        _parser = argparse.ArgumentParser(prog='Model evaluation', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = model_evaluation(**_parsed_args)
      image: python:3.7
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          model_evaluation():\n    return \"Model evaluation completed\"\n\nimport
          argparse\n_parser = argparse.ArgumentParser(prog=''Model evaluation'', description='''')\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = model_evaluation(**_parsed_args)\n"],
          "image": "python:3.7"}}, "name": "Model evaluation"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: smart-e-commerce-pipeline
    dag:
      tasks:
      - name: data-processing
        template: data-processing
        dependencies: [data-scraping]
      - {name: data-scraping, template: data-scraping}
      - name: deploy-model
        template: deploy-model
        dependencies: [model-evaluation]
      - name: ml-training
        template: ml-training
        dependencies: [data-processing]
      - name: model-evaluation
        template: model-evaluation
        dependencies: [ml-training]
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
