apiVersion: argoproj.io/v1alpha1
kind: Pipeline
metadata:
  name: smart-ecommerce-pipeline
  namespace: kubeflow
spec:
  description: "Smart E-commerce AI Pipeline"
  entrypoint: main-pipeline
  templates:
  - name: main-pipeline
    steps:
    - - name: data-scraping
        template: data-scraping
    - - name: data-processing
        template: data-processing
        when: "{{steps.data-scraping.status}} == Succeeded"
    - - name: ml-training
        template: ml-training
        when: "{{steps.data-processing.status}} == Succeeded"
    - - name: model-evaluation
        template: model-evaluation
        when: "{{steps.ml-training.status}} == Succeeded"
    - - name: deploy-model
        template: deploy-model
        when: "{{steps.model-evaluation.status}} == Succeeded"

  - name: data-scraping
    container:
      image: smart-ecommerce-ai-pipeline:latest
      command: [python]
      args: ["-m", "utils.ali_express"]

  - name: data-processing
    container:
      image: smart-ecommerce-ai-pipeline:latest
      command: [python]
      args: ["-m", "utils.data_processor"]

  - name: ml-training
    container:
      image: smart-ecommerce-ai-pipeline:latest
      command: [python]
      args: ["-m", "utils.ml_trainer"]

  - name: model-evaluation
    container:
      image: smart-ecommerce-ai-pipeline:latest
      command: [python]
      args: ["-m", "utils.model_evaluator"]

  - name: deploy-model
    container:
      image: smart-ecommerce-ai-pipeline:latest
      command: [python]
      args: ["-m", "utils.model_deployer"] 