apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ai-pipeline
  labels:
    app: ecommerce-ai-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ai-pipeline
  template:
    metadata:
      labels:
        app: ecommerce-ai-pipeline
    spec:
      containers:
      - name: ecommerce-ai-pipeline
        image: hodaifa485/smart-ecommerce-ml:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-secret
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ai-pipeline-service
spec:
  selector:
    app: ecommerce-ai-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer 