name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Build Docker image
      run: |
        docker build -t ecommerce-ai-pipeline:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      run: |
        docker tag ecommerce-ai-pipeline:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-ai-pipeline:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-ai-pipeline:${{ github.sha }}
    
    - name: Deploy to Minikube
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment/ecommerce-ai-pipeline ecommerce-ai-pipeline=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-ai-pipeline:${{ github.sha }} 