name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-to-local:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Set up Minikube
      uses: medyagh/setup-minikube@master
    
    - name: Deploy to Minikube
      run: |
        # Start Minikube
        minikube start
        
        # Point to Minikube's Docker daemon
        eval $(minikube docker-env)
        
        # Apply Kubernetes configurations
        kubectl apply -f kubeflow_pipelines/mlops-config.yaml
        kubectl apply -f kubeflow_pipelines/deployment.yaml
        kubectl apply -f kubeflow_pipelines/pipeline.yaml
        
        # Wait for deployment
        kubectl rollout status deployment/smart-ecommerce-app -n kubeflow
        
        # Port forward Kubeflow UI
        kubectl port-forward svc/ml-pipeline-ui 8081:80 -n kubeflow &
        
        # Wait for port forwarding to be ready
        sleep 10
        
        # Run the pipeline
        python3 kubeflow_pipelines/automate_pipeline.py 