name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: hodaifa485
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: hodaifa485/smart-ecommerce-ml:latest

  deploy-to-kubeflow:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.b64
        base64 -d kubeconfig.b64 > $HOME/.kube/config
        rm kubeconfig.b64
        chmod 600 $HOME/.kube/config
    
    - name: Apply Kubeflow Pipeline
      run: |
        # Apply Kubernetes configurations
        kubectl apply -f kubeflow_pipelines/mlops-config.yaml
        kubectl apply -f kubeflow_pipelines/deployment.yaml
        kubectl apply -f kubeflow_pipelines/pipeline.yaml
        
        # Run the pipeline
        python3 kubeflow_pipelines/automate_pipeline.py 